/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: danielpaulse (https://sketchfab.com/danielpaulse)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/chess-piece-king-b3e64d44d32b4fb8916f4693460504c5
title: Chess Piece - King
*/

import React, { useContext } from 'react';
import { useGLTF } from '@react-three/drei';
import { positionsContext } from '../components/context';

export function KingModel(props) {
  const { nodes, materials } = useGLTF('/king.gltf');
  const data = useContext(positionsContext);
  
  return (
    <group {...props} dispose={null} onClick={() => {if (props.name) {
      data.setOnPiece({piece: props.name, name: 'k'});
    }
    }}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.02, 0, 0]} scale={300}>
            <mesh geometry={nodes.Object_4.geometry} material={props.color === 'white' ? materials.White_Square : materials.Black_Square} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/king.gltf')
