/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: danielpaulse (https://sketchfab.com/danielpaulse)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/chess-piece-queen-3826ec9d3f91486aa9fd9f30ca934ff8
title: Chess Piece - Queen
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { useContext } from 'react';
import { positionsContext } from '../components/context';

export function QueenModel(props) {
  const { nodes, materials } = useGLTF('/queen.gltf');
  const data = useContext(positionsContext);
  
  return (
    <group {...props} dispose={null} onClick={() => {if (props.name) {
      data.setOnPiece({piece: props.name, name: 'q'});
    }
    }}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.02, 0, 0]} scale={300}>
            <mesh geometry={nodes.Object_6.geometry} material={props.color === 'white' ? materials.White_Square : materials.Black_Square} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/queen.gltf')
