/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: danielpaulse (https://sketchfab.com/danielpaulse)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/chess-piece-rook-4fca9e4f830348279d52b451e64d5e43
title: Chess Piece - Rook
*/

import React, { useContext }  from 'react';
import { useGLTF } from '@react-three/drei';
import { positionsContext } from '../components/context';

export function RookModel(props) {
  const data = useContext(positionsContext);
  const { nodes, materials } = useGLTF('/rook.gltf');

  return (
    <group {...props} dispose={null} onClick={() => {if (props.name) {
      data.setOnPiece({piece: props.name, name: 'r'});
    }
    }}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.02, 0, 0]} scale={280}>
            <mesh geometry={nodes.Object_4.geometry} material={props.color === 'white' ? materials.White_Square : materials.Black_Square} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/rook.gltf');
